#!/bin/sh
# exit code:
# 0: success
# 1: user's error
# 2: compile error

_dwm_dir="./dwm-src"
_blks_dir="./dwmblocks-async"

if [[ -z "$(ls | grep dwm.desktop)" ]]; then
    echo "Wrong directory. Please check if you are in the project root directory."
    exit 1
fi

if [[ "$1" == "clean" ]]; then
	cd $_dwm_dir
	make clean
	exit 0
fi

if [ $(id -u) -ne 0 ]; then
	echo "Please run as root."
	exit 1
fi

msg() {
    echo -e "\e[1;34m==> \e[0m\e[1m$1\e[0m"
}

err() {
    echo -e "\e[1;31m==> $1\e[0m"
}

cd $_dwm_dir
msg "Installing dwm..."
echo " --- dwm ---" > ../make.log

# delete the config.h created by makefile
if [ -f ./config.h ]; then
    rm ./config.h
fi

make >> ../make.log 2>&1
if [ $? -ne 0 ]; then
    err "!! DWM compile error. Please see make.log for details."
    exit 2
fi

echo " --- dwm install ---" >> ../make.log
make install >> ../make.log 2>&1
cd ..

msg "Installing dwmblocks-async..."

cp -fv ./config-dwmblocks.h ./dwmblocks-async/config.h
cp -fv ./config-dwmblocks.c ./dwmblocks-async/config.c

cd $_blks_dir
echo " --- dwmblocks ---" >> ../make.log
make install >> ../make.log 2>&1
if [ $? -ne 0 ]; then
    err "!! dwmblocks compile error. Please see make.log for details."
    exit 2
fi

echo " --- DONE --- " >> ../make.log
msg "Done"
cd ..

msg "Installing files..."

make install_files
