#!/bin/sh
# exit code:
# 0: success
# 1: user's error
# 2: compile error

_dwm_dir="./dwm-src"
_blks_dir="./dwmblocks-async"

if [[ -z "$(ls | grep dwm.desktop)" ]]; then
    echo "Wrong directory. Please check if you are in the project root directory."
    exit 1
fi

if [[ "$1" == "clean" ]]; then
	cd $_dwm_dir
	make clean
	exit 0
fi

if [ $(id -u) -ne 0 ]; then
	echo "Please run as root."
	exit 1
fi

cd $_dwm_dir
echo "==> Installing dwm..."
echo " --- dwm ---" > ../make.log

# delete the config.h created by makefile
if [ -f ./config.h ]; then
    rm ./config.h
fi

make >> ../make.log
if [ $? -ne 0 ]; then
    echo "==> !! DWM compile error. Please see make.log for details."
    exit 2
fi

echo " --- dwm install ---" >> ../make.log
make install >> ../make.log
cd ..

echo "==> Installing dwmblocks-async..."

cp -fv ./config-dwmblocks.h ./dwmblocks-async/config.h
cp -fv ./config-dwmblocks.c ./dwmblocks-async/config.c

cd $_blks_dir
echo " --- dwmblocks ---" >> ../make.log
make install >> ../make.log
if [ $? -ne 0 ]; then
    echo "==> !! dwmblocks compile error. Please see make.log for details."
    exit 2
fi

echo " --- DONE --- " >> ../make.log
echo "==> Done"
cd ..

echo "==> Installing files..."

xsessions_dir="/usr/share/xsessions"
local_bin_dir="/usr/local/bin"

if [ ! -d "$xsessions_dir" ]; then
    echo "$xsessions_dir not found."
	mkdir -pv "$xsessions_dir"
fi
cp -fv ./dwm.desktop $xsessions_dir/dwm.desktop
chmod -v 644 $xsessions_dir/dwm.desktop

if [ ! -d "$local_bin_dir" ]; then
    echo "$local_bin_dir not found."
	mkdir -pv "$local_bin_dir"
fi
cp -fv ./launch_dwm $local_bin_dir/launch_dwm
chmod -v 755 $local_bin_dir/launch_dwm 
