#!/bin/sh

if [[ -z "$DWM_DIR" ]]; then
    export DWM_DIR="$HOME/dwm"
fi

export STATUSBAR="dwmblocks"
export DWM_SCRIPTS="$DWM_DIR/scripts"
export DWM_CONFIG="$DWM_DIR/config"
export DWM_BAR="$DWM_SCRIPTS/bar"

dwmblocks &

while true; do
	# Log stderror to a file
	dwm 2> $HOME/.dwm.log
done

killall dwmblocks
