#!/bin/sh

. $DWM_BAR/update
if [ "$(pamixer --get-mute)" = true ]; then
    update "  " "#999999"
    exit
fi

vol="$(pamixer --get-volume)"
[ $? -ne 0 ] && [ -z "$vol" ] && exit 1

if [ "$vol" -gt 40 ]; then
    icon="  "
elif [ "$vol" -gt 15 ]; then
    icon="  "
else
    icon="  "
fi

update "$vol%" "#404454" "#dfdfff" "$icon" "#232842" "#aaaaba"
